### PR TITLE
Add PPA and Update to Valac 0.32

### PR DESCRIPTION
**Pull request by lewisgoddard**
- Dollar signs stop people copying-and-pasting large blocks of code.
- Add vala ppa to get latest valac and valadoc version.
- Don't assume PHP 5, PHP 7.0 is stable.
- Add unzip to dependancies

### CODE REVIEW

**Comment by benwaffle** [comment]
Let's use `apt` instead of `apt-get`

**Comment by lewisgoddard** [comment]
Really? That makes adding the sources much harder, and the old instructions used `apt-get`. What's the reasoning?

**Comment by benwaffle** [comment]
Literally just replace apt-get with apt

**Comment by lewisgoddard** [comment]
Oh, you mean don't replace the `apt-add-repository` command, despite the actual `apt` command being `apt edit-sources`

I'm still curious as to why there would be a preference for this, when previously `apt-get` was fine?

**Comment by benwaffle** [comment]
Note from apt(8):

```
The apt command is meant to be pleasant for end users and does not need
       to be backward compatible like apt-get(8).
```

https://mvogt.wordpress.com/2014/04/04/apt-1-0/

Of course, `apt-get` works, but we can promote the usage of `apt` in general

**Comment by lewisgoddard** [comment]
Okay, `apt` is more modern.

**Pull request merged**
